### ISSUE TITLE
Add Archetype's Courier DataResolver

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Courier.Contrib#17]
> Copied issue from https://github.com/leekelleher/umbraco-courier-dataresolvers/issues/3

Consider adding [Archetype's Courier DataResolver](https://github.com/kgiszewski/Archetype/blob/master/app/Umbraco/Archetype.Courier/DataResolvers/ArchetypeDataResolver.cs) to this collection.  It would cut down on an extra assembly, which is essentially a single `PropertyDataResolverProvider` class.

The main challenge would be to not have a coupled dependency on the Archetype assembly. Meaning that we would need to create proxy models for `ArchetypeModel` and `ArchetypePreValue`; as well as any helper methods (e.g. `SerializeForPersistence()`).  The goal being that the DataResolver can be portable.

**Comment by sitereactor** [comment]
It would need to be without a direct dependency on Archetype as we can force the dependency on people using this provider. And copying models across to this library is not ideal from a version perspective, so not sure if there is a good approach to this? Open to suggestions

**Comment by leekelleher** [comment]
@sitereactor Yes, agreed - definitely don't to force any 3rd-party dependencies.

When I say "proxy models", I was meaning more to help with deserializing Archetype's JSON data, similar to the [UrlPicker](https://github.com/umbraco/Umbraco.Courier.Contrib/blob/dev/src/Umbraco.Courier.Contrib.Resolvers/PropertyDataResolvers/ImulusUrlPickerPropertyDataResolver.cs#L181) and [Vorto](https://github.com/umbraco/Umbraco.Courier.Contrib/blob/dev/src/Umbraco.Courier.Contrib.Resolvers/PropertyDataResolvers/VortoPropertyDataResolver.cs#L124) resolvers.

**Comment by leekelleher** [comment]
Closing this feature request, as the Archetype project has since been sunset and for those using Archetype + Courier they are most likely already using the existing DataResolver.
