### ISSUE TITLE
Qualification for submission?

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Courier.Contrib#19]
Do we have any guidelines on what qualifies as a popular community package?

I'm currently writing a resolver for our new package, [Stacked Content](https://github.com/umco/umbraco-stacked-content), which is semi-released, (as in it's on NuGet but not on Our yet).  Would this be something worth submitting to this contrib project?

Or would we base it on a certain metric - number of downloads on Our/NuGet, etc?

**Comment by sitereactor** [comment]
If the provider you want to add doesn't require a reference/dependency on a 3rd party (like the actual Stacked Content nuget) then I would say go for it. As long as Courier simply reacts to the DataType/PropertyEditor name then its non-intrusive - as mentioned in the question about Archetype in this Contrib project, that is a bit more challenging.

**Comment by leekelleher** [comment]
Closing this question.

Submitted PR #24 for Stacked Content (Inner Content) data-resolver.
