### ISSUE TITLE
Project name - Courier or Deploy?

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco.Courier.Contrib#2]
I'm not sure what the status is with the renaming of Courier to "Umbraco Deploy", is it worth considering naming this project/repository to be aligned with it?

It would also distance itself from the [old Courier contrib project](https://github.com/umbraco/Courier).

**Comment by clausjensen** [comment]
We're sticking with Courier in the actual project naming to keep things separated. I know it is a bit confusing but I think it will be for the better, since Courier will keep its name and Deploy is a completely new codebase when we get to that point.

**Comment by clausjensen** [comment]
Oh and my plan is to get that old project cleaned up/closed and move the relevant bits to this repository. I'm pretty certain there's a lot of very outdated stuff in there that is causing more trouble than good ;)

**Comment by leekelleher** [comment]
@clausjensen Cool, no worries!
