### ISSUE TITLE
Node id's for multi-url picker not resolved

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Courier.Contrib#29]
I have used the multi-url picker https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker/ inside Archetype for footer content on a Umbraco Cloud project. Previously this was working, but maybe because of updates to Umbraco or Courier the id's are not resolved when deploying e.g. from local to live environment

https://github.com/umbraco/Umbraco.Courier.Contrib/blob/dev/src/Umbraco.Courier.Contrib.Resolvers/PropertyDataResolvers/MultiUrlPickerPropertyDataResolver.cs

I have also added the multi-url picker directly as a property, which has the same issue. Data is deployed, but the node id's are node id's from local environment and therefore it returns an error when clicking edit.

![image](https://cloud.githubusercontent.com/assets/2919859/24591692/cfe4bfba-1807-11e7-87e7-d5feba0a7826.png)

**Comment by bjarnef** [comment]
In the error above the console returns a 404 for /umbraco/backoffice/UmbracoApi/Entity/GetPath?id=1096&type=Document ... where 1096 is the node id for "Garderobe" node on local, but 1272 on live. Both nodes has a guid `77b68ce7-6f32-48b9-9d4c-26e7356b8358`

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply 🙈

I am assuming this issue is long fixed by now so I'm going to close it for now. Let me know if this still needs updating.
