### ISSUE TITLE
Build error - nuget unable to find version 2.52.15 of package 'Courier.Core'

### ISSUE THREAD

**Issue by alindgren** [umbraco/Umbraco.Courier.Contrib#30]
When I try to build, I get an error while trying to restore the Courier.Core nuget package. It is unable to find version 2.52.15 of package 'Courier.Core'.

![screenshot 2017-05-05 14 04 22](https://cloud.githubusercontent.com/assets/910359/25758674/721e7ff6-319d-11e7-9f5a-b297484e3499.png)

I was able to update to the latest 'Courier.Core' by deleting Courier.Core from packages.config and then adding it back with the latest version (I couldn't do it via nuget interface). 

I think either this project needs to be updated to use an available version of Courier.Core (I'll create a pull request), or Courier.Core v 2.52.15 needs to get republished.

**Comment by leekelleher** [comment]
@alindgren Good spot! I hadn't noticed that "Courier.Core" v2.52.x had been removed from the MyGet feed.  I guess it's up to HQ to decide on the minimum supported version of Courier. // @clausjensen

**Comment by Shazwazza** [comment]
I've pushed this back to MyGet, should all be working again.
