### ISSUE TITLE
RJP.MultiUrl Picker no longer functions after installing Courier Contrib

### ISSUE THREAD

**Issue by xman51** [umbraco/Umbraco.Courier.Contrib#37]
```
Exception Details: System.FormatException: Input string was not in a correct format.

Source Error: 

Line 5:  @{
Line 6:  
Line 7:      var linkCollection = CurrentPage.GetPropertyValue<MultiUrls>("importantLinks");
```
This isn't a package that is currently added to Courier contrib so I don't know why this would be happening. Any ideas as to why a non-included package effects another package?

This code is working on the local instance of my project. Only affected is the dev server where I couriered to and the only broken pages are ones where Courier has been used after installing Courier Contrib.

Please advise.

**Comment by clausjensen** [comment]
It is actually covered by Courier.Contrib - was added back in February: https://github.com/umbraco/Umbraco.Courier.Contrib/blob/dev/src/Umbraco.Courier.Contrib.Resolvers/PropertyDataResolvers/MultiUrlPickerPropertyDataResolver.cs
