### ISSUE TITLE
Courier fails if Nested Content textstring contains square brackets

### ISSUE THREAD

**Issue by gordonsaxby** [umbraco/Umbraco.Courier.Contrib#38]
As posted here https://our.umbraco.org/forum/umbraco-courier/87688-courier-fails-if-textstring-contains-and

If a textstring field in a Nested Content datatype contains a string with [ ], for example [[Email]] then Courier fails. Courier works OK if I put the same text ( [[Email]] ) into a textstring field placed directly on a DocType.

**Comment by nul800sebastiaan** [comment]
Sorry for the (very) late reply 🙈

I am assuming this issue is long fixed by now so I'm going to close it for now. Let me know if this still needs updating.
