### ISSUE TITLE
Getting "nullprevalue" where I previously got sourceId->"¤prevalue"->targetId with DropDown and LeBlender

### ISSUE THREAD

**Issue by davidtwamley** [umbraco/Umbraco.Courier.Contrib#39]
I'm still on Umbraco 7.5.11 but tried to jump from Courier 3.0.4 to 3.1.4. When I attempt to use DropDown (pre 7.6) in LeBlender I'm getting "nullprevalue" entries where it failed to resolve a prevalue.

I can imagine [KeyValuePrevalueEditor.cs](https://github.com/umbraco/Courier/blob/master/Providers/Umbraco.Courier.DataResolvers/DataResolvers/KeyValuePrevalueEditor.cs) was updated in relation to [this change](http://issues.umbraco.org/issue/COU-542). Can anyone confirm if the file is stale now. Any chance of updating the public version of that file so I can debug this a bit more? It might shed some light on https://github.com/umbraco/Umbraco.Courier.Contrib/issues/34 too.

Or maybe Courier 3.0.6+ requires Umbraco 7.6+ now and a compatibility warning should go here:  https://our.umbraco.org/projects/umbraco-pro/umbraco-courier/

Thanks!

**Comment by nul800sebastiaan** [comment]
Hey @davidtwamley - Sorry for the (very) late reply 🙈

I am assuming this issue is long fixed by now so I'm going to close it for now. Let me know if this still needs updating.
