### ISSUE TITLE
Update to Nuget package?

### ISSUE THREAD

**Issue by cvocvo** [umbraco/Umbraco.Courier.Contrib#46]
It looks like there's been a few commits to the project since the last version of the nuget package: 1.0.46 on 9/27/18 (almost a year ago :) )

Any chance we can get a nuget update with these recent commits? @nul800sebastiaan @leekelleher @clausjensen 
https://github.com/umbraco/Umbraco.Courier.Contrib/commits/dev

Best,
Chris

**Comment by nul800sebastiaan** [comment]
Sorry for the delay 😰🙈

Done! https://www.nuget.org/packages/Umbraco.Courier.Contrib/1.0.50

**Comment by cvocvo** [comment]
(finally updating this on our projects -- missed your reply initially) @nul800sebastiaan Appreciate it and all the work / future updates! #H5YR
