### ISSUE TITLE
Feature Request: Nuget Package

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco.Courier.Contrib#6]
Hey,

Would be ace if this was available on Nuget, I'm happy to make a PR for this that uses https://www.appveyor.com/ to do the build and deploy... let me know if that is something you wish to add

**Comment by TimGeyssens** [comment]
What I'll need (if you think this is a good idea) is the secure api key from Nuget, you can get the api key from the user that will be the owner of the package at https://www.nuget.org/account (apikey section at the bottom), then take that key and secure it at https://ci.appveyor.com/tools/encrypt

**Comment by TimGeyssens** [comment]
Ok just submitted the pull request #7 (you just need to add your secure nuget api key)

**Comment by clausjensen** [comment]
Thanks @TimGeyssens - will try to take a look at this asap!

**Comment by TimGeyssens** [comment]
No problem glad to contribute :) if you need any help setting it up let me know but once you put in the key it should just work

**Comment by nul800sebastiaan** [comment]
Thanks! It's been pulled in and updated, the patch version increases by 1 with each AppVeyor build (1.0.1, 1.0.2, etc). I think it's the easiest way and it's all automatic so we can't forget to update the version. Just need to check with @clausjensen if he's OK with that. 
The build is here: https://ci.appveyor.com/project/Umbraco/umbraco-courier-contrib

Also not sure if we should automatically publish each successful build to NuGet. On the other hand, it's a tiny library, so why not?

**Comment by leekelleher** [comment]
re: pushing builds to NuGet - maybe it's better to have a "develop" branch, then merge in actual releases with the "master", which would then do the NuGet push, etc.  Just thinking that a "build" doesn't necessarily equal a "release".  (_Just my 2 cents worth_ 😉)

**Comment by TimGeyssens** [comment]
Yup good point @leekelleher

**Comment by leekelleher** [comment]
Noticed that the "dev" branch has pushed a new NuGet release.  Just checking if this is intentional?

AppVeyor CI: <https://ci.appveyor.com/project/Umbraco/umbraco-courier-contrib/build/1.0.13>
NuGet: <https://www.nuget.org/packages/Umbraco.Courier.Contrib/1.0.13>

I'm happy to send a PR to update `appveyor.yml` to include...

```yaml
deploy:
  provider: NuGet
  # snipped
  on:
      branch: master
```

**Comment by clausjensen** [comment]
Wasn't really - the idea was to only push NuGet's from `master` so sounds like we need to get that updated.

**Comment by leekelleher** [comment]
@clausjensen I'll send over a PR 👍

**Comment by clausjensen** [comment]
@leekelleher Thanks 😃
